### ISSUE TITLE
Memory leak on test

### ISSUE THREAD

**Issue by dvtkrlbs** [LeonineKing1199/minivec#1]
I run your test suit using miri and there is a small leak
```rust
running 33 tests
test minivec_as_mut ... ok
test minivec_dedup_by_test ... ok
test minivec_dedup_needs_drop ... ok
test minivec_default_constructed ... ok
test minivec_deref_test ... ok
test minivec_extend ... ok
test minivec_extend_from_slice ... ok
test minivec_from ... ok
test minivec_from_raw_part ... ok
test minivec_from_raw_parts ... ok
test minivec_hash ... ok
test minivec_index ... ok
test minivec_insert ... ok
test minivec_into_iter ... ok
test minivec_leak ... ok
test minivec_macro ... ok
test minivec_pop ... ok
test minivec_push ... ok
test minivec_remove ... ok
test minivec_remove_item ... ok
test minivec_remove_panic ... ok
test minivec_resize_with ... ok
test minivec_retain ... ok
test minivec_shrink_to ... ok
test minivec_shrink_to_panic ... ok
test minivec_splice ... ok
test minivec_splice_raii ... ok
test minivec_split_off ... ok
test minivec_swap_remove ... ok
test minivec_test_resize ... ok
test minivec_truncate ... ok
test minivec_with_capacity ... ok
test minvec_drain ... ok

test result: ok. 33 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out

The following memory was leaked: alloc300481 (Rust heap, size: 56, align: 8) {
    0x00 │ ╾a300481+0x18[<untagged>] (8 ptr bytes)╼ 03 00 00 00 00 00 00 00 │ ╾──────╼........
    0x10 │ 04 00 00 00 00 00 00 00 02 00 00 00 00 00 00 00 │ ................
    0x20 │ 02 00 00 00 00 00 00 00 03 00 00 00 00 00 00 00 │ ................
    0x30 │ __ __ __ __ __ __ __ __                         │ ░░░░░░░░
}

error: the evaluated program leaked memory

error: aborting due to previous error

error: test failed, to rerun pass '--test mine'
```

I am on macOS

**Comment by LeonineKing1199** [comment]
I'm actually impressed that Miri ran for you. I tried it in the past and it wasn't as effective as running the code through valgrind was.

Anyway, that leak is known and actually quite deliberate.

It happens here: https://github.com/LeonineKing1199/minivec/blob/d7af2441f184e7ffd72e2c2df4c32f34f37dc2be/tests/mine.rs#L238

It was to make sure that `leak` actually leaked and I relied on valgrind to pick that up for me. Right now this test is a little flimsy and there's actually more idiomatic ways of making sure that a destructor wasn't run.

If you'd like, a PR improving this test would be appreciated.

**Comment by dvtkrlbs** [comment]
```rust
#[test]
fn minivec_leak() {
	let mut static_ref: &'static mut [usize];
	{
    	let x = mini_vec![1, 2, 3];
    	static_ref = MiniVec::leak(x);
	}
    static_ref[0] += 1;
    assert_eq!(static_ref, &[2, 2, 3]);

	// and call the drop method manually maybe
}
```

i have this in mind i will create a pr tonight what do you think ?

**Comment by Plecra** [comment]
It seems like it'd be best to avoid testing for UB... how about this?

```rust
struct HasDropped<'a>(&'a mut bool);
impl Drop for HasDropped<'_> {
    fn drop(&mut self) {
        *self.0 = true;
    }
}
let mut has_dropped = false;
{
    let leaked = MiniVec::leak(mini_vec![HasDropped(&mut has_dropped)]);
}
assert!(!has_dropped);
```

...or maybe there's a way to require that a test is run through miri?

**Comment by Plecra** [comment]
Either way, testing `leak` will need to leak an allocation. I think it's simplest to just `#[cfg_attr(miri, ignore)]` on the `minivec_leak` test

**Comment by LeonineKing1199** [comment]
Actually,
```rust
struct HasDropped<'a>(&'a mut bool);
impl Drop for HasDropped<'_> {
    fn drop(&mut self) {
        *self.0 = true;
    }
}
let mut has_dropped = false;
{
    let leaked = MiniVec::leak(mini_vec![HasDropped(&mut has_dropped)]);
}
assert!(!has_dropped);
```
is exactly what I had in mind!

I see there's a PR to have miri simply ignore the leak. I'd much rather see this test inside the codebase instead.

One thing I'd like to prove in the test is that Dropping actually works too. So maybe something that `pop`s off a few elements and then leaks.

**Comment by Plecra** [comment]
Supporting MIRI and improving the `Drop` tests are two different issues, and I'd recommend handling them as separate contributions. It's mostly for the sake of making the project more welcoming for contributors by creating for hoops to jump through for positive changes (of course, you're right to reject changes that aren't suitable).

Another option would be to guarantee that `MiniVec::from_raw` is valid on a `&'static mut [T]` returned from `Minivec::leak`, and use that to clean up the test. If not, an exception would have to be made to support running the tests in MIRI

**Comment by LeonineKing1199** [comment]
Alright, sounds fair to me. I'll merge the PR for the Miri fix.
