### ISSUE TITLE
Remove `Header.data_`

### ISSUE THREAD

**Issue by Plecra** [LeonineKing1199/minivec#2]
I think it's possible to calculate on the spot as `ptr.offset(T::OFFSET_CONSTANT)`, which will be faster and use less space.

It would also make the representation more intuitive, since the way `Header` is defined at the moment gives the impression that `data_` owns another allocation

**Comment by Plecra** [comment]
I investigated a little, and I'm pretty sure this is an appropriate alternative:

```rust
use alloc::alloc::{alloc, dealloc, handle_alloc_error, realloc, Layout};
use core::mem;
use core::ptr;

pub struct MiniVec<T> {
    /// A pointer to an `Inner<T>` followed by and array of `cap` `T`s.
    // `usize::MAX - size_of::<Inner<T>>()` could be used for the empty vector optimisation,
    // since it could only ever represent an empty buffer anyway
    ptr: ptr::NonNull<Inner<T>>,
}

struct Inner<T> {
    cap: usize,
    len: usize,
    #[allow(unused)]
    data: [T; 0],
}

impl<T> MiniVec<T> {
    pub fn with_capacity(capacity: usize) -> Self {
        let layout = Layout::array::<T>(capacity)
            .and_then(|slots| Layout::new::<Inner<T>>().extend(slots))
            .expect("capacity overflow")
            .0;
        let ptr = ptr::NonNull::new(unsafe { alloc(layout) } as *mut Inner<T>)
            .unwrap_or_else(|| handle_alloc_error(layout));

        unsafe {
            ptr::write(
                ptr.as_ptr(),
                Inner {
                    cap: capacity,
                    len: 0,
                    data: [],
                },
            )
        }

        Self { ptr }
    }
    // `Drop` and `IntoIter as Drop` are implemented with this
    fn current_memory(&self) -> (ptr::NonNull<u8>, Layout) {
        (
            self.ptr.cast(),
            Layout::array::<T>(self.capacity())
                .and_then(|slots| Layout::new::<Inner<T>>().extend(slots))
                .expect("`self` in invalid state")
                .0,
        )
    }
    // `reserve` and `shrink` are implemented with this
    fn realloc(&mut self, capacity: usize) {
        let (ptr, layout) = self.current_memory();
        let new_size = Layout::array::<T>(capacity)
            .expect("capacity overflow")
            .size();
        self.ptr =
            ptr::NonNull::new(unsafe { realloc(ptr.as_ptr(), layout, new_size) } as *mut Inner<T>)
                .unwrap_or_else(|| handle_alloc_error(layout));
        self.inner_mut().cap = capacity;
    }
    fn inner(&self) -> &Inner<T> {
        unsafe { &*self.ptr.as_ptr() }
    }
    fn inner_mut(&mut self) -> &mut Inner<T> {
        unsafe { &mut *self.ptr.as_ptr() }
    }
    pub fn len(&self) -> usize {
        self.inner().len
    }
    pub fn capacity(&self) -> usize {
        self.inner().cap
    }
    pub fn as_mut_ptr(&mut self) -> *mut T {
        (unsafe { self.ptr.as_ptr().add(1) }) as *mut T
    }
    pub fn as_mut_slice(&mut self) -> &mut [T] {
        unsafe { core::slice::from_raw_parts_mut(self.as_mut_ptr(), self.len()) }
    }
}
```

It's also much simpler, since it relies on Rust's native layout code to figure out alignment.

**Comment by LeonineKing1199** [comment]
How do we handle `NonNull` needing to be null when created via `MiniVec::new`?

**Comment by Plecra** [comment]
`NonNull::dangling` can't be used for this: There's no way to check if an existing `NonNull` is dangling.

> Note that the pointer value may potentially represent a valid pointer to a T, which means this must not be used as a "not yet initialized" sentinel value.

Is there something wrong the the `usize::MAX - size_of::<Inner<T>>()` solution I mentioned in the original code?

**Comment by LeonineKing1199** [comment]
> Is there something wrong with the usize::MAX - size_of::<Inner<T>>() solution I mentioned in the original code?

It's fine!

Though I must confess... I'm not sure of the inherent benefits of refactoring the code this way. I can guess the value in adding a `NonNull` optimization to the internal raw pointer.

But I'm having trouble seeing the inherent value in such a deep refactor into how the allocations are performed. Which isn't to say that I'm closed off to them. But I'm curious what they bring to the table vs what we have now which is much more akin to how a dinosaur C++ programmer (like me) would write it in the language they're familiar with.

**Comment by LeonineKing1199** [comment]
Explicit `*mut T` member removed by: https://github.com/LeonineKing1199/minivec/pull/7
